name:                church-encoding
version:             0.1.0.0
github:              "githubuser/church-encoding"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/church-encoding#readme>

dependencies:
- containers >= 0.6.5.1 && < 0.7
- QuickCheck >= 2.14.2 && < 7
- base >=4.7 && <5

library:
  ghc-options:
    - -Wall
    - -Wmissing-local-signatures
  source-dirs: src


tests:
  church-encoding-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - church-encoding
